let employees = [
    {
        "photo": null,
        "firstName": "John",
        "lastName": "Doe",
        "dob": "1990-05-12",
        "employeeId": "EMP001",
        "email": "john.doe@example.com",
        "employeeType": "Chef",
        "employeeStatus": "Active",
        "department": "Kitchen",
        "city": "New York",
        "pin": "10001",
        "pan": "ABCDE1234F",
        "salary": "50000",
        "dateOfHire": "2022-03-15",
        "employeeEndDate": ""
    },
    {
        "photo": null,
        "firstName": "Sarah",
        "lastName": "Smith",
        "dob": "1988-08-22",
        "employeeId": "EMP002",
        "email": "sarah.smith@example.com",
        "employeeType": "Manager",
        "employeeStatus": "Active",
        "department": "Management",
        "city": "Los Angeles",
        "pin": "90001",
        "pan": "FGHIJ5678K",
        "salary": "70000",
        "dateOfHire": "2021-06-10",
        "employeeEndDate": ""
    },
    {
        "photo": null,
        "firstName": "David",
        "lastName": "Brown",
        "dob": "1995-02-14",
        "employeeId": "EMP003",
        "email": "david.brown@example.com",
        "employeeType": "Waiter",
        "employeeStatus": "Active",
        "department": "Service",
        "city": "Chicago",
        "pin": "60601",
        "pan": "KLMNO9101P",
        "salary": "30000",
        "dateOfHire": "2023-01-20",
        "employeeEndDate": ""
    },
    {
        "photo": null,
        "firstName": "Emily",
        "lastName": "Johnson",
        "dob": "1992-11-30",
        "employeeId": "EMP004",
        "email": "emily.johnson@example.com",
        "employeeType": "Sous Chef",
        "employeeStatus": "Active",
        "department": "Kitchen",
        "city": "Houston",
        "pin": "77001",
        "pan": "PQRST2345U",
        "salary": "45000",
        "dateOfHire": "2022-07-05",
        "employeeEndDate": ""
    },
    {
        "photo": null,
        "firstName": "Michael",
        "lastName": "Williams",
        "dob": "1985-04-18",
        "employeeId": "EMP005",
        "email": "michael.williams@example.com",
        "employeeType": "Bartender",
        "employeeStatus": "Active",
        "department": "Bar",
        "city": "Phoenix",
        "pin": "85001",
        "pan": "UVWXY6789Z",
        "salary": "40000",
        "dateOfHire": "2020-09-12",
        "employeeEndDate": ""
    },
    {
        "photo": null,
        "firstName": "Jessica",
        "lastName": "Taylor",
        "dob": "1998-07-25",
        "employeeId": "EMP006",
        "email": "jessica.taylor@example.com",
        "employeeType": "Waitress",
        "employeeStatus": "Active",
        "department": "Service",
        "city": "San Diego",
        "pin": "92101",
        "pan": "ABCDE5432F",
        "salary": "32000",
        "dateOfHire": "2024-02-01",
        "employeeEndDate": ""
    },
    {
        "photo": null,
        "firstName": "Daniel",
        "lastName": "Martinez",
        "dob": "1987-09-08",
        "employeeId": "EMP007",
        "email": "daniel.martinez@example.com",
        "employeeType": "Head Chef",
        "employeeStatus": "Active",
        "department": "Kitchen",
        "city": "Dallas",
        "pin": "75201",
        "pan": "JKLMN8765P",
        "salary": "80000",
        "dateOfHire": "2018-05-22",
        "employeeEndDate": ""
    },
    {
        "photo": null,
        "firstName": "Laura",
        "lastName": "Harris",
        "dob": "1993-12-05",
        "employeeId": "EMP008",
        "email": "laura.harris@example.com",
        "employeeType": "Hostess",
        "employeeStatus": "Active",
        "department": "Front Desk",
        "city": "San Antonio",
        "pin": "78201",
        "pan": "OPQRS5678T",
        "salary": "35000",
        "dateOfHire": "2023-06-30",
        "employeeEndDate": ""
    },
    {
        "photo": null,
        "firstName": "Kevin",
        "lastName": "Anderson",
        "dob": "1991-06-17",
        "employeeId": "EMP009",
        "email": "kevin.anderson@example.com",
        "employeeType": "Dishwasher",
        "employeeStatus": "Active",
        "department": "Kitchen",
        "city": "Philadelphia",
        "pin": "19101",
        "pan": "TUVWX4321Y",
        "salary": "25000",
        "dateOfHire": "2024-01-10",
        "employeeEndDate": ""
    },
    {
        "photo": null,
        "firstName": "Sophia",
        "lastName": "Moore",
        "dob": "1989-03-03",
        "employeeId": "EMP010",
        "email": "sophia.moore@example.com",
        "employeeType": "Cashier",
        "employeeStatus": "Active",
        "department": "Billing",
        "city": "San Francisco",
        "pin": "94101",
        "pan": "ZABCD1234E",
        "salary": "38000",
        "dateOfHire": "2021-11-15",
        "employeeEndDate": ""
    }
]


export default employees